# Generated by Django 3.1.7 on 2021-06-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email_aluno', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=255, verbose_name='Nome do Livro')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('autor_livro', models.CharField(max_length=255, verbose_name='Autor do Livro')),
                ('resumo_livro', models.TextField(max_length=255)),
                ('editora', models.CharField(max_length=255, verbose_name='Editora')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenaçao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Curso')),
                ('data_inicio', models.DateField(verbose_name='Data de Início do Semestre')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão do Curso')),
                ('grade_curricular', models.TextField(blank=True, null=True, verbose_name='Grade Curricular')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Mensalidade')),
                ('email_aluno', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_aluno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.aluno', verbose_name='Nome do Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seu_nome', models.CharField(max_length=255, verbose_name='Seu Nome')),
                ('seu_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resumo_duvida', models.CharField(max_length=255, verbose_name='Resumo da Dúvida')),
                ('duvida', models.TextField(verbose_name='Escreva sua Dúvida')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Dúvida')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_evento', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('hora', models.TimeField(verbose_name='Hora do Evento')),
                ('data_e_hora', models.DateTimeField(verbose_name='Data e Hora do Evento')),
                ('resumo', models.CharField(max_length=255, verbose_name='Resumo do Evento')),
                ('observacao', models.TextField(verbose_name='Observações sobre o Evento')),
                ('palestrante', models.CharField(max_length=255, verbose_name='Nome do Palestrante')),
                ('email_palestrante', models.EmailField(blank=True, max_length=254, null=True)),
                ('cursos_obrigatorios', models.CharField(max_length=255)),
                ('cursos_opcionais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lanche', models.CharField(max_length=255)),
                ('ingredientes', models.TextField()),
                ('numero_produto', models.IntegerField(default=0, verbose_name='Numero do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.DateField(verbose_name='Semestre')),
                ('qtd_alunos', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Quantidade de Alunos')),
                ('vagas_totais', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Total de Vagas')),
                ('vagas_remanescentes', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Vagas Remanescentes')),
                ('data_de_inicio', models.DateField(verbose_name='Data de Início do Curso')),
                ('data_de_conclusao', models.DateField(verbose_name='Data de Conclusão de Curso')),
                ('nome_do_curso', models.ManyToManyField(to='blog.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('Sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('Idade', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Idade')),
                ('email_aluno', models.EmailField(blank=True, max_length=254, null=True)),
                ('senha', models.CharField(max_length=16)),
                ('confirmar_senha', models.CharField(max_length=16)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('conclusao_em', models.DateField(verbose_name='Data de Conclusão do Ensino Médio')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('curso', models.ManyToManyField(to='blog.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Cantina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_fabricacao', models.DateField(verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('observacao', models.TextField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qtd_itens', models.IntegerField(blank=True, default=0, verbose_name='Quantidade de Itens')),
                ('lanche', models.ManyToManyField(to='blog.Lanche')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_p1', models.DateField(verbose_name='Data da prova 1')),
                ('hora_p1', models.TimeField(verbose_name='Hora da Prova 1')),
                ('data_p2', models.DateField(verbose_name='Data da Prova 2')),
                ('hora_p2', models.TimeField(verbose_name='Hora da Prova 2')),
                ('nome_curso', models.ManyToManyField(to='blog.Curso')),
            ],
        ),
    ]
